name: auto-merge-codex
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    if: github.event.pull_request.user.login == 'codex'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: |
          git fetch origin main --prune
          git merge -X ours origin/main --no-edit
      - run: git push origin HEAD:${{ github.event.pull_request.head.ref }}

      - name: Merge into main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch --admin
