name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Check for bare imports
        run: node scripts/lint-no-bare-imports.js

      - name: Bundle sources
        run: npm run bundle

      - name: Ensure preload bundle exists
        run: |
          if (-not (Test-Path 'dist/preload.js')) {
            Write-Error 'dist/preload.js missing'
            exit 1
          }
        shell: pwsh

      - name: Run unit tests
        run: npm test

      - name: Bundle sources
        run: npm run bundle

      - name: Build portable win32
        run: npm run build:win32       # electron-builder --win portable

      - name: Upload portable EXE
        uses: actions/upload-artifact@v4
        with:
          name: partner-dashboard-win
          path: dist/*.exe
