name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Check for bare imports
        run: node scripts/lint-no-bare-imports.js

      - name: Run unit tests
        run: npm test

  win-package:
    needs: test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build:dir

      - run: node scripts/verify-preload-in-asar.js dist/win-unpacked/resources/app.asar

      - run: electron-builder --win portable

      - name: Verify preload in portable
        shell: pwsh
        run: |
          7z e -aoa (Get-ChildItem -Path dist -Filter *.exe).FullName resources/app.asar -odist/extracted
          node scripts/verify-preload-in-asar.js dist/extracted/app.asar

      - uses: actions/upload-artifact@v4
        with:
          name: partner-dashboard-win
          path: dist/*.exe
